### ISSUE TITLE
[bug] swagen 同时存在 ns 和 ns_like query

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#117]
### bug 描述

可以说是bug 也可以说是一个逻辑冲突

openapi.yml 的query parameter 中 

```
        - name: ns_like
          in: query
          description: Which namespace users blong to, regix
          required: false
          schema:
            type: string
        - name: ns
          in: query
          description: Which namespace users blong to
          required: false
          schema:
            type: string
```

此时 ns 会被翻译成 ns?: string

忽略了 { $regex: string } 的形式

## 解决办法

两个选择

1. typings 中 ns 支持多格式
2. 给 ns_like 一个独立的字段
