### ISSUE TITLE
[bug] swagen不支持id参数

### ISSUE THREAD

**Issue by MiffyLiye** [36node/sketch#142]
### bug 描述

在openapi.yml中定义
```
        - name: id
          in: query
          description: 根据vin码查询车辆
          required: false
          schema:
            type: string
```
运行```yarn gen:api```后报错
```
$ swagen koa openapi.yml ./src/api
{ SyntaxError: Type expected. (16:17)
  14 |         num?: string;
  15 |         _id: {
> 16 |             0?: ;
     |                 ^
  17 |             1?: ;
  18 |         }
  19 |         plate?: string;
    at e (/Users/miffyliye/Code/36node/bus-core/node_modules/prettier/parser-typescript.js:1:329)
    at Object.parse (/Users/miffyliye/Code/36node/bus-core/node_modules/prettier/parser-typescript.js:1:2261443)
    at Object.parse$2 [as parse] (/Users/miffyliye/Code/36node/bus-core/node_modules/prettier/index.js:10633:19)
    at coreFormat (/Users/miffyliye/Code/36node/bus-core/node_modules/prettier/index.js:13842:23)
    at format (/Users/miffyliye/Code/36node/bus-core/node_modules/prettier/index.js:14100:73)
    at formatWithCursor (/Users/miffyliye/Code/36node/bus-core/node_modules/prettier/index.js:14116:12)
    at /Users/miffyliye/Code/36node/bus-core/node_modules/prettier/index.js:42527:15
    at Object.format (/Users/miffyliye/Code/36node/bus-core/node_modules/prettier/index.js:42546:12)
    at g (/Users/miffyliye/Code/36node/bus-core/node_modules/@36node/swagen/dist/index.js:1:6612)
    at /Users/miffyliye/Code/36node/bus-core/node_modules/@36node/swagen/dist/index.js:1:9624
  loc: { start: { line: 16, column: 17 } },
  codeFrame:
   '\u001b[0m \u001b[90m 14 | \u001b[39m        num\u001b[33m?\u001b[39m\u001b[33m:\u001b[39m string\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 15 | \u001b[39m        _id\u001b[33m:\u001b[39m {\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 16 | \u001b[39m            \u001b[35m0\u001b[39m\u001b[33m?\u001b[39m\u001b[33m:\u001b[39m \u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m                \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 17 | \u001b[39m            \u001b[35m1\u001b[39m\u001b[33m?\u001b[39m\u001b[33m:\u001b[39m \u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 18 | \u001b[39m        }\u001b[0m\n\u001b[0m \u001b[90m 19 | \u001b[39m        plate\u001b[33m?\u001b[39m\u001b[33m:\u001b[39m string\u001b[33m;\u001b[39m\u001b[0m' }
```

使用vin代替id
```
        - name: vin
          in: query
          description: 根据vin码查询车辆
          required: false
          schema:
            type: string
```
则没有问题
