### ISSUE TITLE
[feature] tpl-service openapi 中支持 nullable 配置

### ISSUE THREAD

**Issue by magiccaptain** [36node/sketch#197]
### 需求描述

可在openapi中的schema中配置 nullable， 比如：

```yml
  schemas:
    PetDoc:
      type: object
      properties:
        name:
          type: string
          description: pet's name
        tag:
          type: string
          enum: ["DOG", "CAT"]
        age:
          type: integer
          format: int32
        birthAt:
          type: string
          format: date
          nullable: true
        grade:
          type: integer
          format: int32
        owner:
          type: string
        other1:
          type: string
          readOnly: true
        other2:
          type: string
          writeOnly: true
```

然后生成的 ajv schema 可通过 null 值

现在无法生效的原因在于 openapi 支持nullable 写法， 但是ajv 不支持 nullable， nullable 对应的ajv 写法为 type: ['string', 'null']

这里无需修改swagen，只需参考 validator 中间件中的 lowerCaseHeaders 方法，把每个配置有nullable 的 schema.type 变为 ['string', 'null'] 格式
